file1=input("enter file 1")
file2= input("enter file 2")
f1=open(file1,'r')
f2=open(file2,'w')
cont=f1.readlines()
for i in range(0,len(cont)):
    f2.write(cont[i])
f2.close()
print("contents of first file copies to second")
f2=open(file2,'r')
cont1=f2.read()
print("content of second file is : ")
print(cont1)
f1.close()
f2.close()
